extends:
  - eslint:recommended
  - plugin:import/recommended
  - plugin:import/typescript
  - plugin:react/recommended
  - plugin:@typescript-eslint/eslint-recommended
  - plugin:@typescript-eslint/recommended-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
env:
  browser: true
  node: true
  es6: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: true
  sourceType: module
  ecmaVersion: latest
  ecmaFeatures:
    jsx: true
plugins:
  - '@stylistic/eslint-plugin'
  - '@typescript-eslint'
  - react
settings:
  import/resolver:
    typescript:
      project: './frontend/tsconfig.json'
  react:
    version: 'detect'
root: true
rules:
  no-console: error
  no-control-regex: off
  import/default: off
  import/no-named-as-default-member: off
  react/jsx-key: error
  react/prop-types: off
  react/display-name: off
  '@typescript-eslint/no-empty-interface': off
  '@typescript-eslint/no-unsafe-assignment': off
  '@typescript-eslint/no-unsafe-member-access': off
  '@typescript-eslint/consistent-type-definitions': off
  '@typescript-eslint/explicit-function-return-type':
    - error
    - allowExpressions: true

  '@stylistic/comma-dangle':
    - error
    - always-multiline
  '@stylistic/indent':
    - error
    - 2
  '@stylistic/quotes':
    - error
    - single
    - avoidEscape: true
  '@stylistic/semi':
    - error
    - never